### ISSUE TITLE
2.1 todo list

### ISSUE THREAD

**Issue by object-Object** [object-Object/Yotogi#1]
**Commands**
- [x] move

**Settings**
- [x] warning_kick_level
- [x] warning_ban_level
- [x] default_mute_length
- [x] warning_length

**Other**
- [x] rename to Yot
