### ISSUE TITLE
Long-term todo list

### ISSUE THREAD

**Issue by object-Object** [object-Object/Yotogi#3]
These are things that I want to add to the bot, but not necessarily in any specific update (i.e. whenever I feel like putting in the work to add these, I'll make a new minor version for them).

**Commands**
- [ ] remind

**Features**
- [ ] command to create Muted role

**Other**
- [ ] wiki on GitHub
- [ ] restructure database to try and get rid of the json
