### ISSUE TITLE
Checklist for moving all output strings to lang/en-CA.json

### ISSUE THREAD

**Issue by object-Object** [object-Object/Yotogi#5]
Need to go through each of these files and put their output strings into lang/en-CA.json. (This is literally just a list of every .lua file in the repo)

- [x] options.lua
- [x] modules/client/messageUpdate/message-edit-logger.lua
- [x] modules/client/memberLeave/persistent-roles-leave.lua
- [x] modules/client/memberLeave/mute-manager-leave.lua
- [x] modules/client/memberLeave/warning-manager-leave.lua
- [x] modules/client/messageDelete/message-delete-logger.lua
- [x] modules/client/messageCreate/youtube-anti-ad.lua
- [x] modules/client/messageCreate/suggestions-channel.lua
- [x] modules/client/messageCreate/discord-anti-ad.lua
- [x] modules/client/memberJoin/warning-manager-join.lua
- [x] modules/client/memberJoin/mute-manager-join.lua
- [x] modules/client/memberJoin/persistent-roles-join.lua
- [x] modules/client/userBan/ban-messages.lua
- [x] modules/clock/min/mute-manager.lua
- [x] modules/clock/min/warning-manager.lua
- [x] libs/miscUtils.lua
- [x] libs/moduleHandler.lua
- [x] libs/warnUtils.lua
- [x] libs/muteUtils.lua
- [x] libs/commandHandler.lua
- [x] create-db.lua
- [x] commands/Moderation/unban.lua
- [x] commands/Moderation/unwarn.lua
- [x] commands/Moderation/warn.lua
- [x] commands/Moderation/move.lua
- [x] commands/Moderation/ban.lua
- [x] commands/Moderation/mute.lua
- [x] commands/Moderation/unmute.lua
- [x] commands/Moderation/kick.lua
- [x] commands/Info/ping.lua
- [x] commands/Info/changelog.lua
- [x] commands/Info/help.lua
- [x] commands/Info/about.lua
- [x] commands/Config/prefix.lua
- [x] commands/Utility/avatar.lua
- [x] commands/Utility/members.lua
- [x] commands/Utility/mention.lua
- [x] commands/Utility/warnings.lua
- [x] commands/Utility/channels.lua
- [x] commands/.Owner/restart.lua
- [x] commands/.Owner/lua.lua
- [x] yot.lua
- [x] modules/client/memberJoin/join-messages.lua
- [x] modules/client/memberLeave/leave-messages.lua
